/* import the fontawesome core */
import { library } from "@fortawesome/fontawesome-svg-core";

/* import font awesome icon component */
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";

/* import icons and add them to the Library */
import {
  faHome,
  faHouse,
  faBell,
  faMessage,
  faBagShopping,
  faComments,
  faCommentDots,
  faCalendarCheck,
  faPhone,
  faVideo,
  faArrowRight,
  faArrowLeft,
  faUsers,
  faUserPlus,
  faDoorOpen,
  faSearch,
  faPaperPlane,
  faUser,
  faStar,
  faMicrophone,
  faMicrophoneSlash,
  faPhoneSlash,
  faVideoSlash,
  faAddressCard,
  faVialVirus,
  faFlaskVial,
  faHandHoldingMedical,
  faCartShopping,
  faXmark,
  faCircleCheck,
  faUserPen,
  faFileMedical,
  faCreditCard,
  faGear,
  faChevronRight,
  faArrowRightToBracket,
  faEye,
  faPaw,
  faLock,
  faStore,
  faBoxOpen,
  faFolderTree,
  faPlus,
  faPen,
  faTrash,
  faRotate,
  faFloppyDisk,
  faEdit,
  faCheck,
  faChevronDown,
} from "@fortawesome/free-solid-svg-icons";

import {
  faCircle,
  faCircleDot,
  faSquare,
  faSquareCheck,
} from "@fortawesome/free-regular-svg-icons";

library.add(
  faHome,
  faHouse,
  faBell,
  faMessage,
  faBagShopping,
  faComments,
  faCommentDots,
  faCalendarCheck,
  faPhone,
  faVideo,
  faVideoSlash,
  faArrowRight,
  faArrowLeft,
  faUsers,
  faUserPlus,
  faDoorOpen,
  faSearch,
  faPaperPlane,
  faUser,
  faStar,
  faMicrophone,
  faMicrophoneSlash,
  faPhoneSlash,
  faVideoSlash,
  faAddressCard,
  faVialVirus,
  faFlaskVial,
  faHandHoldingMedical,
  faCartShopping,
  faXmark,
  faCircleCheck,
  faUserPen,
  faFileMedical,
  faCreditCard,
  faGear,
  faChevronRight,
  faArrowRightToBracket,
  faEye,
  faPaw,
  faLock,
  faStore,
  faBoxOpen,
  faFolderTree,
  faPlus,
  faPen,
  faTrash,
  faRotate,
  faFloppyDisk,
  faEdit,
  faCheck,
  faChevronDown,
  faCircle,
  faCircleDot,
  faSquare,
  faSquareCheck
);

export { FontAwesomeIcon };
