/* import the fontawesome core */
import { library } from "@fortawesome/fontawesome-svg-core";

/* import font awesome icon component */
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";

/* import icons and add them to the Library */
import {
  faAddressCard,
  faArrowLeft,
  faArrowRight,
  faArrowRightToBracket,
  faBagShopping,
  faBell,
  faBoxOpen,
  faCalendarCheck,
  faCartShopping,
  faCheck,
  faChevronDown,
  faChevronRight,
  faCircleCheck,
  faCommentDots,
  faComments,
  faCreditCard,
  faDatabase,
  faDoorOpen,
  faDownload,
  faEdit,
  faEye,
  faEyeSlash,
  faFileMedical,
  faFlaskVial,
  faFloppyDisk,
  faFolderOpen,
  faFolderTree,
  faGear,
  faHandHoldingMedical,
  faHardDrive,
  faHome,
  faHouse,
  faLock,
  faMessage,
  faMicrophone,
  faMicrophoneSlash,
  faPaperPlane,
  faPaw,
  faPen,
  faPhone,
  faPhoneSlash,
  faPlus,
  faRotate,
  faSearch,
  faStar,
  faStore,
  faTrash,
  faUser,
  faUserPen,
  faUserPlus,
  faUsers,
  faVialVirus,
  faVideo,
  faVideoSlash,
  faXmark,
} from "@fortawesome/free-solid-svg-icons";

import {
  faCircle,
  faCircleDot,
  faSquare,
  faSquareCheck,
} from "@fortawesome/free-regular-svg-icons";

library.add(
  faAddressCard,
  faArrowLeft,
  faArrowRight,
  faArrowRightToBracket,
  faBagShopping,
  faBell,
  faBoxOpen,
  faCalendarCheck,
  faCartShopping,
  faCheck,
  faChevronDown,
  faChevronRight,
  faCircleCheck,
  faCommentDots,
  faComments,
  faCreditCard,
  faDatabase,
  faDoorOpen,
  faDownload,
  faEdit,
  faEye,
  faEyeSlash,
  faFileMedical,
  faFlaskVial,
  faFloppyDisk,
  faFolderOpen,
  faFolderTree,
  faGear,
  faHandHoldingMedical,
  faHardDrive,
  faHome,
  faHouse,
  faLock,
  faMessage,
  faMicrophone,
  faMicrophoneSlash,
  faPaperPlane,
  faPaw,
  faPen,
  faPhone,
  faPhoneSlash,
  faPlus,
  faRotate,
  faSearch,
  faStar,
  faStore,
  faTrash,
  faUser,
  faUserPen,
  faUserPlus,
  faUsers,
  faVialVirus,
  faVideo,
  faVideoSlash,
  faXmark,
  faCircle,
  faCircleDot,
  faSquare,
  faSquareCheck
);

export { FontAwesomeIcon };
