/** Auto-generated by vue-nnn-router — do not edit */
export const ROUTER_NAME = {
  adminBackup: "admin-backup",
  adminDashboard: "admin-dashboard",
  adminLogin: "admin-login",
  adminRedirect: "admin-redirect",
  adminUsers: "admin-users",
  adminUsersAdd: "admin-users-add",
  adminUsersId: "admin-users-id",
  rootLayout: "root-layout",

} as const;

export type RouterName = (typeof ROUTER_NAME)[keyof typeof ROUTER_NAME];
