/** Auto-generated by vue-nnn-router — do not edit */
export const ROUTER_NAME = {
  adminDashboard: "admin-dashboard",
  adminLayout: "admin-layout",
  adminRedirect: "admin-redirect",
  adminUsers: "admin-users",
  adminUsersAdd: "admin-users-add",
  adminUsersId: "admin-users-id",
  home: "home",
  login: "login",

} as const;

export type RouterName = (typeof ROUTER_NAME)[keyof typeof ROUTER_NAME];
